name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build binaries
    runs-on: windows-2022
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:          
      - name: Check out files
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=Win32 build/iw4x.sln

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/Win32/${{matrix.configuration}}/iw4x.dll
            build/bin/Win32/${{matrix.configuration}}/iw4x.pdb

  deploy:
    name: Deploy artifacts
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop')
    steps:
      - name: Setup develop environment
        if: github.ref == 'refs/heads/develop'
        run: echo "DIAMANTE_MASTER_PATH=${{ secrets.DIAMANTE_MASTER_SSH_PATH }}" >> $GITHUB_ENV

      - name: Download Release binaries
        uses: actions/download-artifact@v3.0.2
        with:
          name: Release binaries

      # Set up committer info and GPG key
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.DIAMANTE_MASTER_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.DIAMANTE_MASTER_SSH_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Upload iw4x-client binary
        run: rsync -avz iw4x.dll ${{ secrets.DIAMANTE_MASTER_SSH_USER }}@${{ secrets.DIAMANTE_MASTER_SSH_ADDRESS }}:${{ env.DIAMANTE_MASTER_PATH }}/iw4/

      - name: Publish changes
        run: ssh ${{ secrets.DIAMANTE_MASTER_SSH_USER }}@${{ secrets.DIAMANTE_MASTER_SSH_ADDRESS }} ${{ secrets.DIAMANTE_SSH_CHANGE_PUBLISH_COMMAND }}
